# coding: utf-8

"""
    RAI Cloud SDK

    This is a Client SDK for RAI Cloud  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class CreateComputeRequestProtocol(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'region': 'str',
        'name': 'str',
        'size': 'str',
        'dryrun': 'bool'
    }

    attribute_map = {
        'region': 'region',
        'name': 'name',
        'size': 'size',
        'dryrun': 'dryrun'
    }

    def __init__(self, region=None, name=None, size=None, dryrun=None, local_vars_configuration=None):  # noqa: E501
        """CreateComputeRequestProtocol - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._region = None
        self._name = None
        self._size = None
        self._dryrun = None
        self.discriminator = None

        if region is not None:
            self.region = region
        if name is not None:
            self.name = name
        if size is not None:
            self.size = size
        if dryrun is not None:
            self.dryrun = dryrun

    @property
    def region(self):
        """Gets the region of this CreateComputeRequestProtocol.  # noqa: E501


        :return: The region of this CreateComputeRequestProtocol.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this CreateComputeRequestProtocol.


        :param region: The region of this CreateComputeRequestProtocol.  # noqa: E501
        :type region: str
        """

        self._region = region

    @property
    def name(self):
        """Gets the name of this CreateComputeRequestProtocol.  # noqa: E501


        :return: The name of this CreateComputeRequestProtocol.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateComputeRequestProtocol.


        :param name: The name of this CreateComputeRequestProtocol.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def size(self):
        """Gets the size of this CreateComputeRequestProtocol.  # noqa: E501


        :return: The size of this CreateComputeRequestProtocol.  # noqa: E501
        :rtype: str
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this CreateComputeRequestProtocol.


        :param size: The size of this CreateComputeRequestProtocol.  # noqa: E501
        :type size: str
        """

        self._size = size

    @property
    def dryrun(self):
        """Gets the dryrun of this CreateComputeRequestProtocol.  # noqa: E501


        :return: The dryrun of this CreateComputeRequestProtocol.  # noqa: E501
        :rtype: bool
        """
        return self._dryrun

    @dryrun.setter
    def dryrun(self, dryrun):
        """Sets the dryrun of this CreateComputeRequestProtocol.


        :param dryrun: The dryrun of this CreateComputeRequestProtocol.  # noqa: E501
        :type dryrun: bool
        """

        self._dryrun = dryrun

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateComputeRequestProtocol):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateComputeRequestProtocol):
            return True

        return self.to_dict() != other.to_dict()
