# coding: utf-8

"""
    RAI Cloud SDK

    This is a Client SDK for RAI Cloud  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ListComputesResponseProtocol(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'computes': 'list[ComputeInfoProtocol]'
    }

    attribute_map = {
        'computes': 'computes'
    }

    def __init__(self, computes=None, local_vars_configuration=None):  # noqa: E501
        """ListComputesResponseProtocol - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._computes = None
        self.discriminator = None

        if computes is not None:
            self.computes = computes

    @property
    def computes(self):
        """Gets the computes of this ListComputesResponseProtocol.  # noqa: E501


        :return: The computes of this ListComputesResponseProtocol.  # noqa: E501
        :rtype: list[ComputeInfoProtocol]
        """
        return self._computes

    @computes.setter
    def computes(self, computes):
        """Sets the computes of this ListComputesResponseProtocol.


        :param computes: The computes of this ListComputesResponseProtocol.  # noqa: E501
        :type computes: list[ComputeInfoProtocol]
        """

        self._computes = computes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListComputesResponseProtocol):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListComputesResponseProtocol):
            return True

        return self.to_dict() != other.to_dict()
