"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.csv_file_syntax import CSVFileSyntax
from rai_api.model.json_file_syntax import JSONFileSyntax
globals()['CSVFileSyntax'] = CSVFileSyntax
globals()['JSONFileSyntax'] = JSONFileSyntax
from rai_api.model.file_syntax import FileSyntax


class TestFileSyntax(unittest.TestCase):
    """FileSyntax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileSyntax(self):
        """Test FileSyntax"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FileSyntax()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
