"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.abstract_problem import AbstractProblem
from rai_api.model.exception_problem_all_of import ExceptionProblemAllOf
globals()['AbstractProblem'] = AbstractProblem
globals()['ExceptionProblemAllOf'] = ExceptionProblemAllOf
from rai_api.model.persist_problem import PersistProblem


class TestPersistProblem(unittest.TestCase):
    """PersistProblem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPersistProblem(self):
        """Test PersistProblem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PersistProblem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
