"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.source import Source
globals()['Source'] = Source
from rai_api.model.install_action_all_of import InstallActionAllOf


class TestInstallActionAllOf(unittest.TestCase):
    """InstallActionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstallActionAllOf(self):
        """Test InstallActionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstallActionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
