"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.abstract_problem import AbstractProblem
from rai_api.model.linked_list import LinkedList
from rai_api.model.syntax_error_all_of import SyntaxErrorAllOf
from rai_api.model.syntax_node import SyntaxNode
globals()['AbstractProblem'] = AbstractProblem
globals()['LinkedList'] = LinkedList
globals()['SyntaxErrorAllOf'] = SyntaxErrorAllOf
globals()['SyntaxNode'] = SyntaxNode
from rai_api.model.syntax_error import SyntaxError


class TestSyntaxError(unittest.TestCase):
    """SyntaxError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSyntaxError(self):
        """Test SyntaxError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SyntaxError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
