"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.cardinality_action_all_of import CardinalityActionAllOf


class TestCardinalityActionAllOf(unittest.TestCase):
    """CardinalityActionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCardinalityActionAllOf(self):
        """Test CardinalityActionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CardinalityActionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
