"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.range import Range
globals()['Range'] = Range
from rai_api.model.token_all_of import TokenAllOf


class TestTokenAllOf(unittest.TestCase):
    """TokenAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenAllOf(self):
        """Test TokenAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TokenAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
