"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.csv_file_schema_all_of import CSVFileSchemaAllOf
from rai_api.model.file_schema import FileSchema
globals()['CSVFileSchemaAllOf'] = CSVFileSchemaAllOf
globals()['FileSchema'] = FileSchema
from rai_api.model.csv_file_schema import CSVFileSchema


class TestCSVFileSchema(unittest.TestCase):
    """CSVFileSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCSVFileSchema(self):
        """Test CSVFileSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CSVFileSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
