"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.linked_list import LinkedList
from rai_api.model.syntax_node import SyntaxNode
globals()['LinkedList'] = LinkedList
globals()['SyntaxNode'] = SyntaxNode
from rai_api.model.syntax_error_all_of import SyntaxErrorAllOf


class TestSyntaxErrorAllOf(unittest.TestCase):
    """SyntaxErrorAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSyntaxErrorAllOf(self):
        """Test SyntaxErrorAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SyntaxErrorAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
