# coding: utf-8

"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.update_action_all_of import UpdateActionAllOf  # noqa: E501
from openapi_client.rest import ApiException

class TestUpdateActionAllOf(unittest.TestCase):
    """UpdateActionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UpdateActionAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.update_action_all_of.UpdateActionAllOf()  # noqa: E501
        if include_optional :
            return UpdateActionAllOf(
                delta = [
                    openapi_client.models.pair_any_value_any_value_.Pair_AnyValue_AnyValue_(
                        first = null, 
                        second = null, 
                        type = 'Pair_AnyValue_AnyValue_', )
                    ], 
                rel = openapi_client.models.rel_key.RelKey(
                    keys = [
                        '0'
                        ], 
                    name = '0', 
                    values = [
                        '0'
                        ], 
                    type = 'RelKey', ), 
                updates = [
                    openapi_client.models.pair_any_value_any_value_.Pair_AnyValue_AnyValue_(
                        first = null, 
                        second = null, 
                        type = 'Pair_AnyValue_AnyValue_', )
                    ]
            )
        else :
            return UpdateActionAllOf(
                rel = openapi_client.models.rel_key.RelKey(
                    keys = [
                        '0'
                        ], 
                    name = '0', 
                    values = [
                        '0'
                        ], 
                    type = 'RelKey', ),
        )

    def testUpdateActionAllOf(self):
        """Test UpdateActionAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
