"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.ic_violation import ICViolation
globals()['ICViolation'] = ICViolation
from rai_api.model.integrity_constraint_violation_all_of import IntegrityConstraintViolationAllOf


class TestIntegrityConstraintViolationAllOf(unittest.TestCase):
    """IntegrityConstraintViolationAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIntegrityConstraintViolationAllOf(self):
        """Test IntegrityConstraintViolationAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IntegrityConstraintViolationAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
