"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.pair_symbol_string import PairSymbolString


class TestPairSymbolString(unittest.TestCase):
    """PairSymbolString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPairSymbolString(self):
        """Test PairSymbolString"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PairSymbolString()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
