"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.action import Action
globals()['Action'] = Action
from rai_api.model.labeled_action import LabeledAction


class TestLabeledAction(unittest.TestCase):
    """LabeledAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabeledAction(self):
        """Test LabeledAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LabeledAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
