"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.set_options_action_all_of import SetOptionsActionAllOf


class TestSetOptionsActionAllOf(unittest.TestCase):
    """SetOptionsActionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetOptionsActionAllOf(self):
        """Test SetOptionsActionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SetOptionsActionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
