"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.source import Source
globals()['Source'] = Source
from rai_api.model.parse_action_all_of import ParseActionAllOf


class TestParseActionAllOf(unittest.TestCase):
    """ParseActionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParseActionAllOf(self):
        """Test ParseActionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParseActionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
