"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.collect_problems_action_all_of import CollectProblemsActionAllOf
from rai_api.model.linked_list import LinkedList
globals()['CollectProblemsActionAllOf'] = CollectProblemsActionAllOf
globals()['LinkedList'] = LinkedList
from rai_api.model.nil import Nil


class TestNil(unittest.TestCase):
    """Nil unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNil(self):
        """Test Nil"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Nil()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
