"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.relation import Relation
globals()['Relation'] = Relation
from rai_api.model.import_action_all_of import ImportActionAllOf


class TestImportActionAllOf(unittest.TestCase):
    """ImportActionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImportActionAllOf(self):
        """Test ImportActionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ImportActionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
