"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.action import Action
from rai_api.model.modify_workspace_action_all_of import ModifyWorkspaceActionAllOf
globals()['Action'] = Action
globals()['ModifyWorkspaceActionAllOf'] = ModifyWorkspaceActionAllOf
from rai_api.model.modify_workspace_action import ModifyWorkspaceAction


class TestModifyWorkspaceAction(unittest.TestCase):
    """ModifyWorkspaceAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifyWorkspaceAction(self):
        """Test ModifyWorkspaceAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModifyWorkspaceAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
