# coding: utf-8

"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.token_all_of import TokenAllOf  # noqa: E501
from openapi_client.rest import ApiException

class TestTokenAllOf(unittest.TestCase):
    """TokenAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TokenAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.token_all_of.TokenAllOf()  # noqa: E501
        if include_optional :
            return TokenAllOf(
                range = openapi_client.models.range.Range(
                    area = openapi_client.models.area.Area(
                        end_point = openapi_client.models.point.Point(
                            column = 56, 
                            row = 56, 
                            type = 'Point', ), 
                        start_point = openapi_client.models.point.Point(
                            column = 56, 
                            row = 56, 
                            type = 'Point', ), 
                        type = 'Area', ), 
                    end_byte = 56, 
                    input = null, 
                    start_byte = 56, 
                    type = 'Range', ), 
                value = '0'
            )
        else :
            return TokenAllOf(
                range = openapi_client.models.range.Range(
                    area = openapi_client.models.area.Area(
                        end_point = openapi_client.models.point.Point(
                            column = 56, 
                            row = 56, 
                            type = 'Point', ), 
                        start_point = openapi_client.models.point.Point(
                            column = 56, 
                            row = 56, 
                            type = 'Point', ), 
                        type = 'Area', ), 
                    end_byte = 56, 
                    input = null, 
                    start_byte = 56, 
                    type = 'Range', ),
                value = '0',
        )

    def testTokenAllOf(self):
        """Test TokenAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
