"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.load_data import LoadData
globals()['LoadData'] = LoadData
from rai_api.model.load_data_action_all_of import LoadDataActionAllOf


class TestLoadDataActionAllOf(unittest.TestCase):
    """LoadDataActionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoadDataActionAllOf(self):
        """Test LoadDataActionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoadDataActionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
