# coding: utf-8

"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.integrity_constraint_violation_all_of import IntegrityConstraintViolationAllOf  # noqa: E501
from openapi_client.rest import ApiException

class TestIntegrityConstraintViolationAllOf(unittest.TestCase):
    """IntegrityConstraintViolationAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IntegrityConstraintViolationAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.integrity_constraint_violation_all_of.IntegrityConstraintViolationAllOf()  # noqa: E501
        if include_optional :
            return IntegrityConstraintViolationAllOf(
                sources = [
                    openapi_client.models.ic_violation.ICViolation(
                        rel_key = openapi_client.models.rel_key.RelKey(
                            keys = [
                                '0'
                                ], 
                            name = '0', 
                            values = [
                                '0'
                                ], 
                            type = 'RelKey', ), 
                        source = '0', 
                        type = 'ICViolation', )
                    ]
            )
        else :
            return IntegrityConstraintViolationAllOf(
        )

    def testIntegrityConstraintViolationAllOf(self):
        """Test IntegrityConstraintViolationAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
