"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.client_problem_all_of import ClientProblemAllOf


class TestClientProblemAllOf(unittest.TestCase):
    """ClientProblemAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientProblemAllOf(self):
        """Test ClientProblemAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClientProblemAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
