"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.relation import Relation
from rai_api.model.source import Source
globals()['Relation'] = Relation
globals()['Source'] = Source
from rai_api.model.query_action_all_of import QueryActionAllOf


class TestQueryActionAllOf(unittest.TestCase):
    """QueryActionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryActionAllOf(self):
        """Test QueryActionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QueryActionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
