"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.collect_problems_action_all_of import CollectProblemsActionAllOf
from rai_api.model.integration import Integration
globals()['CollectProblemsActionAllOf'] = CollectProblemsActionAllOf
globals()['Integration'] = Integration
from rai_api.model.s3_integration import S3Integration


class TestS3Integration(unittest.TestCase):
    """S3Integration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testS3Integration(self):
        """Test S3Integration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = S3Integration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
