"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.file_schema import FileSchema
from rai_api.model.file_syntax import FileSyntax
from rai_api.model.integration import Integration
globals()['FileSchema'] = FileSchema
globals()['FileSyntax'] = FileSyntax
globals()['Integration'] = Integration
from rai_api.model.load_data import LoadData


class TestLoadData(unittest.TestCase):
    """LoadData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoadData(self):
        """Test LoadData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoadData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
