"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.rel_key import RelKey
globals()['RelKey'] = RelKey
from rai_api.model.ic_violation import ICViolation


class TestICViolation(unittest.TestCase):
    """ICViolation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testICViolation(self):
        """Test ICViolation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ICViolation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
