"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.area import Area
globals()['Area'] = Area
from rai_api.model.range import Range


class TestRange(unittest.TestCase):
    """Range unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRange(self):
        """Test Range"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Range()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
