"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.range import Range
from rai_api.model.syntax_node import SyntaxNode
globals()['Range'] = Range
globals()['SyntaxNode'] = SyntaxNode
from rai_api.model.appl_all_of import ApplAllOf


class TestApplAllOf(unittest.TestCase):
    """ApplAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplAllOf(self):
        """Test ApplAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
