"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.abstract_problem import AbstractProblem
from rai_api.model.ic_violation import ICViolation
from rai_api.model.integrity_constraint_violation_all_of import IntegrityConstraintViolationAllOf
globals()['AbstractProblem'] = AbstractProblem
globals()['ICViolation'] = ICViolation
globals()['IntegrityConstraintViolationAllOf'] = IntegrityConstraintViolationAllOf
from rai_api.model.integrity_constraint_violation import IntegrityConstraintViolation


class TestIntegrityConstraintViolation(unittest.TestCase):
    """IntegrityConstraintViolation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIntegrityConstraintViolation(self):
        """Test IntegrityConstraintViolation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IntegrityConstraintViolation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
