"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.rel_key import RelKey


class TestRelKey(unittest.TestCase):
    """RelKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRelKey(self):
        """Test RelKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RelKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
