"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.csv_file_syntax_all_of import CSVFileSyntaxAllOf


class TestCSVFileSyntaxAllOf(unittest.TestCase):
    """CSVFileSyntaxAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCSVFileSyntaxAllOf(self):
        """Test CSVFileSyntaxAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CSVFileSyntaxAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
