"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.cons import Cons
from rai_api.model.nil import Nil
globals()['Cons'] = Cons
globals()['Nil'] = Nil
from rai_api.model.linked_list import LinkedList


class TestLinkedList(unittest.TestCase):
    """LinkedList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkedList(self):
        """Test LinkedList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LinkedList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
