"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.csv_file_schema import CSVFileSchema
from rai_api.model.json_file_schema import JSONFileSchema
globals()['CSVFileSchema'] = CSVFileSchema
globals()['JSONFileSchema'] = JSONFileSchema
from rai_api.model.file_schema import FileSchema


class TestFileSchema(unittest.TestCase):
    """FileSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileSchema(self):
        """Test FileSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FileSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
