"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.abstract_problem import AbstractProblem
from rai_api.model.integrity_constraint_problem_all_of import IntegrityConstraintProblemAllOf
globals()['AbstractProblem'] = AbstractProblem
globals()['IntegrityConstraintProblemAllOf'] = IntegrityConstraintProblemAllOf
from rai_api.model.storage_problem import StorageProblem


class TestStorageProblem(unittest.TestCase):
    """StorageProblem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageProblem(self):
        """Test StorageProblem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StorageProblem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
