"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.collect_problems_action_all_of import CollectProblemsActionAllOf
from rai_api.model.file_syntax import FileSyntax
globals()['CollectProblemsActionAllOf'] = CollectProblemsActionAllOf
globals()['FileSyntax'] = FileSyntax
from rai_api.model.json_file_syntax import JSONFileSyntax


class TestJSONFileSyntax(unittest.TestCase):
    """JSONFileSyntax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJSONFileSyntax(self):
        """Test JSONFileSyntax"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JSONFileSyntax()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
