"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.cardinality_action import CardinalityAction
from rai_api.model.collect_problems_action import CollectProblemsAction
from rai_api.model.import_action import ImportAction
from rai_api.model.install_action import InstallAction
from rai_api.model.list_edb_action import ListEdbAction
from rai_api.model.list_source_action import ListSourceAction
from rai_api.model.load_data_action import LoadDataAction
from rai_api.model.modify_workspace_action import ModifyWorkspaceAction
from rai_api.model.parse_action import ParseAction
from rai_api.model.query_action import QueryAction
from rai_api.model.set_options_action import SetOptionsAction
from rai_api.model.status_action import StatusAction
from rai_api.model.update_action import UpdateAction
globals()['CardinalityAction'] = CardinalityAction
globals()['CollectProblemsAction'] = CollectProblemsAction
globals()['ImportAction'] = ImportAction
globals()['InstallAction'] = InstallAction
globals()['ListEdbAction'] = ListEdbAction
globals()['ListSourceAction'] = ListSourceAction
globals()['LoadDataAction'] = LoadDataAction
globals()['ModifyWorkspaceAction'] = ModifyWorkspaceAction
globals()['ParseAction'] = ParseAction
globals()['QueryAction'] = QueryAction
globals()['SetOptionsAction'] = SetOptionsAction
globals()['StatusAction'] = StatusAction
globals()['UpdateAction'] = UpdateAction
from rai_api.model.action import Action


class TestAction(unittest.TestCase):
    """Action unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAction(self):
        """Test Action"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Action()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
