"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.action import Action
from rai_api.model.load_data import LoadData
from rai_api.model.load_data_action_all_of import LoadDataActionAllOf
globals()['Action'] = Action
globals()['LoadData'] = LoadData
globals()['LoadDataActionAllOf'] = LoadDataActionAllOf
from rai_api.model.load_data_action import LoadDataAction


class TestLoadDataAction(unittest.TestCase):
    """LoadDataAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoadDataAction(self):
        """Test LoadDataAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoadDataAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
