"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.range import Range
globals()['Range'] = Range
from rai_api.model.literal_all_of import LiteralAllOf


class TestLiteralAllOf(unittest.TestCase):
    """LiteralAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLiteralAllOf(self):
        """Test LiteralAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LiteralAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
