"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.pair_any_value_any_value import PairAnyValueAnyValue
from rai_api.model.rel_key import RelKey
globals()['PairAnyValueAnyValue'] = PairAnyValueAnyValue
globals()['RelKey'] = RelKey
from rai_api.model.update_action_all_of import UpdateActionAllOf


class TestUpdateActionAllOf(unittest.TestCase):
    """UpdateActionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateActionAllOf(self):
        """Test UpdateActionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateActionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
