"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.collect_problems_action_all_of import CollectProblemsActionAllOf
from rai_api.model.integration import Integration
globals()['CollectProblemsActionAllOf'] = CollectProblemsActionAllOf
globals()['Integration'] = Integration
from rai_api.model.default_integration import DefaultIntegration


class TestDefaultIntegration(unittest.TestCase):
    """DefaultIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDefaultIntegration(self):
        """Test DefaultIntegration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DefaultIntegration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
