"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.csv_file_syntax_all_of import CSVFileSyntaxAllOf
from rai_api.model.file_syntax import FileSyntax
globals()['CSVFileSyntaxAllOf'] = CSVFileSyntaxAllOf
globals()['FileSyntax'] = FileSyntax
from rai_api.model.csv_file_syntax import CSVFileSyntax


class TestCSVFileSyntax(unittest.TestCase):
    """CSVFileSyntax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCSVFileSyntax(self):
        """Test CSVFileSyntax"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CSVFileSyntax()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
