"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.range import Range
from rai_api.model.syntax_node import SyntaxNode
from rai_api.model.token_all_of import TokenAllOf
globals()['Range'] = Range
globals()['SyntaxNode'] = SyntaxNode
globals()['TokenAllOf'] = TokenAllOf
from rai_api.model.token import Token


class TestToken(unittest.TestCase):
    """Token unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testToken(self):
        """Test Token"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Token()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
