"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.point import Point
globals()['Point'] = Point
from rai_api.model.area import Area


class TestArea(unittest.TestCase):
    """Area unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArea(self):
        """Test Area"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Area()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
