"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.action import Action
from rai_api.model.import_action_all_of import ImportActionAllOf
from rai_api.model.relation import Relation
globals()['Action'] = Action
globals()['ImportActionAllOf'] = ImportActionAllOf
globals()['Relation'] = Relation
from rai_api.model.import_action import ImportAction


class TestImportAction(unittest.TestCase):
    """ImportAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImportAction(self):
        """Test ImportAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ImportAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
