"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rai_api
from rai_api.model.azure_integration_all_of import AzureIntegrationAllOf
from rai_api.model.integration import Integration
from rai_api.model.pair_symbol_string import PairSymbolString
globals()['AzureIntegrationAllOf'] = AzureIntegrationAllOf
globals()['Integration'] = Integration
globals()['PairSymbolString'] = PairSymbolString
from rai_api.model.azure_integration import AzureIntegration


class TestAzureIntegration(unittest.TestCase):
    """AzureIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAzureIntegration(self):
        """Test AzureIntegration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AzureIntegration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
