# coding: utf-8

"""
    Delve Client SDK

    This is a Client SDK for Delve API  # noqa: E501

    The version of the OpenAPI document: 1.1.3
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class AzureIntegrationAllOf(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'credentials': 'list[PairSymbolString]',
        'name': 'str',
        'storage_allowed_locations': 'list[str]',
        'storage_blocked_locations': 'list[str]',
        'tenant_id': 'str'
    }

    attribute_map = {
        'credentials': 'credentials',
        'name': 'name',
        'storage_allowed_locations': 'storage_allowed_locations',
        'storage_blocked_locations': 'storage_blocked_locations',
        'tenant_id': 'tenant_id'
    }

    def __init__(self, credentials=None, name=None, storage_allowed_locations=None, storage_blocked_locations=None, tenant_id=None, local_vars_configuration=None):  # noqa: E501
        """AzureIntegrationAllOf - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._credentials = None
        self._name = None
        self._storage_allowed_locations = None
        self._storage_blocked_locations = None
        self._tenant_id = None
        self.discriminator = None

        self.credentials = credentials
        self.name = name
        self.storage_allowed_locations = storage_allowed_locations
        self.storage_blocked_locations = storage_blocked_locations
        self.tenant_id = tenant_id

    @property
    def credentials(self):
        """Gets the credentials of this AzureIntegrationAllOf.  # noqa: E501


        :return: The credentials of this AzureIntegrationAllOf.  # noqa: E501
        :rtype: list[PairSymbolString]
        """
        return self._credentials

    @credentials.setter
    def credentials(self, credentials):
        """Sets the credentials of this AzureIntegrationAllOf.


        :param credentials: The credentials of this AzureIntegrationAllOf.  # noqa: E501
        :type credentials: list[PairSymbolString]
        """

        self._credentials = credentials

    @property
    def name(self):
        """Gets the name of this AzureIntegrationAllOf.  # noqa: E501


        :return: The name of this AzureIntegrationAllOf.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AzureIntegrationAllOf.


        :param name: The name of this AzureIntegrationAllOf.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def storage_allowed_locations(self):
        """Gets the storage_allowed_locations of this AzureIntegrationAllOf.  # noqa: E501


        :return: The storage_allowed_locations of this AzureIntegrationAllOf.  # noqa: E501
        :rtype: list[str]
        """
        return self._storage_allowed_locations

    @storage_allowed_locations.setter
    def storage_allowed_locations(self, storage_allowed_locations):
        """Sets the storage_allowed_locations of this AzureIntegrationAllOf.


        :param storage_allowed_locations: The storage_allowed_locations of this AzureIntegrationAllOf.  # noqa: E501
        :type storage_allowed_locations: list[str]
        """

        self._storage_allowed_locations = storage_allowed_locations

    @property
    def storage_blocked_locations(self):
        """Gets the storage_blocked_locations of this AzureIntegrationAllOf.  # noqa: E501


        :return: The storage_blocked_locations of this AzureIntegrationAllOf.  # noqa: E501
        :rtype: list[str]
        """
        return self._storage_blocked_locations

    @storage_blocked_locations.setter
    def storage_blocked_locations(self, storage_blocked_locations):
        """Sets the storage_blocked_locations of this AzureIntegrationAllOf.


        :param storage_blocked_locations: The storage_blocked_locations of this AzureIntegrationAllOf.  # noqa: E501
        :type storage_blocked_locations: list[str]
        """

        self._storage_blocked_locations = storage_blocked_locations

    @property
    def tenant_id(self):
        """Gets the tenant_id of this AzureIntegrationAllOf.  # noqa: E501


        :return: The tenant_id of this AzureIntegrationAllOf.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this AzureIntegrationAllOf.


        :param tenant_id: The tenant_id of this AzureIntegrationAllOf.  # noqa: E501
        :type tenant_id: str
        """

        self._tenant_id = tenant_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AzureIntegrationAllOf):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AzureIntegrationAllOf):
            return True

        return self.to_dict() != other.to_dict()
