# coding: utf-8

"""
    RAI Cloud SDK

    This is a Client SDK for RAI Cloud  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account_credits_get(self):
        """Test case for account_credits_get

        Get account credits consumption  # noqa: E501
        """
        pass

    def test_compute_delete(self):
        """Test case for compute_delete

        Delete compute  # noqa: E501
        """
        pass

    def test_compute_get(self):
        """Test case for compute_get

        List computes  # noqa: E501
        """
        pass

    def test_compute_put(self):
        """Test case for compute_put

        Create compute  # noqa: E501
        """
        pass

    def test_database_get(self):
        """Test case for database_get

        List databases  # noqa: E501
        """
        pass

    def test_database_post(self):
        """Test case for database_post

        Update database  # noqa: E501
        """
        pass

    def test_list_compute_events(self):
        """Test case for list_compute_events

        List compute events  # noqa: E501
        """
        pass

    def test_user_get(self):
        """Test case for user_get

        List users  # noqa: E501
        """
        pass

    def test_user_put(self):
        """Test case for user_put

        Create user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
