# coding: utf-8

"""
    RAI Cloud SDK

    This is a Client SDK for RAI Cloud  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.create_compute_request_protocol import CreateComputeRequestProtocol  # noqa: E501
from openapi_client.rest import ApiException

class TestCreateComputeRequestProtocol(unittest.TestCase):
    """CreateComputeRequestProtocol unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateComputeRequestProtocol
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.create_compute_request_protocol.CreateComputeRequestProtocol()  # noqa: E501
        if include_optional :
            return CreateComputeRequestProtocol(
                region = '0', 
                name = '0', 
                size = '0', 
                dryrun = True
            )
        else :
            return CreateComputeRequestProtocol(
        )

    def testCreateComputeRequestProtocol(self):
        """Test CreateComputeRequestProtocol"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
