# coding: utf-8

"""
    RAI Cloud SDK

    This is a Client SDK for RAI Cloud  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Contact: support@relational.ai
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.compute_event_info import ComputeEventInfo  # noqa: E501
from openapi_client.rest import ApiException

class TestComputeEventInfo(unittest.TestCase):
    """ComputeEventInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ComputeEventInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.compute_event_info.ComputeEventInfo()  # noqa: E501
        if include_optional :
            return ComputeEventInfo(
                event_id = '0', 
                account_name = '0', 
                compute_id = '0', 
                event = '0', 
                time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return ComputeEventInfo(
        )

    def testComputeEventInfo(self):
        """Test ComputeEventInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
