name: Build and publish poetry package
on:
  push:
    branches:
     - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          version: 1.1.6
      - name: Build Project
        run: poetry build
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish
